<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="T_LabourList.aspx.cs" Inherits="Crud_V2.UI.T_LabourList" %>

<%@ Register Assembly="CrystalDecisions.Web, Version=13.0.3500.0, Culture=neutral, PublicKeyToken=692fbea5521e1304" Namespace="CrystalDecisions.Web" TagPrefix="CR" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

           


    <fieldset>

        <legend>Input Form</legend>

        <table class="table table-border">

            <tr>
                <td>
                    <asp:Label ID="lbl_id" runat="server" Text="Employee ID"></asp:Label></td>
                <td>
                    <asp:TextBox ID="txtbox_employeeid" runat="server" CssClass="form-control"></asp:TextBox></td>
                <td>
                    <asp:Button ID="btn_refresh" runat="server" Text="Add New User" CssClass="btn btn-info" OnClick="btn_refresh_Click" />
                </td>

            </tr>

            <tr>
                <td>
                    <asp:Label ID="lbl_name" runat="server" Text="Name"></asp:Label></td>
                <td>
                    <asp:TextBox ID="txtbox_name" runat="server" CssClass="form-control"></asp:TextBox></td>

            </tr>

            <tr>
                <td>
                    <asp:Label ID="lbl_mail" runat="server" Text="Mail"></asp:Label></td>
                <td>
                    <asp:TextBox ID="txtbox_mail" runat="server" CssClass="form-control"></asp:TextBox></td>
                <td>
                    <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ErrorMessage="Incorrect Email Format" ControlToValidate="txtbox_mail" ForeColor="Red" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator></td>
            </tr>


            <tr>
                <td>
                    <asp:Label ID="lbl_department" runat="server" Text="Department"></asp:Label></td>
                <td>
                    <asp:TextBox ID="txtbox_department" runat="server" CssClass="form-control"></asp:TextBox></td>
            </tr>

            <tr>
                <td>
                    <asp:Label ID="lbl_designation" runat="server" Text="Designation"></asp:Label></td>
                <td>
                    <asp:TextBox ID="txtbox_designation" runat="server" CssClass="form-control"></asp:TextBox></td>
            </tr>


            <tr>
                <td>
                    <asp:Label ID="lbl_join_date" runat="server" Text="Joining Date"></asp:Label></td>
                <td>
                    <asp:TextBox ID="txtbox_join_date" runat="server" CssClass="form-control"></asp:TextBox>

                </td>
            </tr>


            <tr>
                <td>
                    <asp:Label ID="lbl_salary" runat="server" Text="Salary"></asp:Label></td>
                <td>
                    <asp:TextBox ID="txtbox_salary" runat="server" CssClass="form-control"></asp:TextBox></td>
            </tr>

            <tr>
                <td>
                    <asp:Button ID="btnEmpSave" runat="server" Text="Insert" CssClass="btn btn-primary" OnClick="btnEmpSave_Click" />
                </td>
                <td>
                    <asp:Button ID="btn_update" runat="server" Text="Update" CssClass="btn btn-success" OnClick="btn_update_Click" /></td>
                <td>
                    <asp:Button ID="btn_labourReport" runat="server" Text="Labour Report" CssClass="btn btn-default" OnClick="btn_labourReport_Click" />
                </td>

            </tr>
        </table>
    </fieldset>



    <fieldset>

        <asp:GridView ID="gv_T_LabourInfo" runat="server" CssClass="table" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="gv_T_LabourInfo_RowDeleting" OnSelectedIndexChanged="gv_T_LabourInfo_SelectedIndexChanged">

            <Columns>
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:LinkButton Text="Select" ID="lnkSelect" runat="server" CommandName="Select" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="EmployeeID">
                    <ItemTemplate>
                        <asp:Label ID="lbl_id" Text='<%# Eval("EmployeeID") %>' runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Name">
                    <ItemTemplate>
                        <asp:Label ID="lbl_EmployeeName" Text='<%# Eval("EmployeeName") %>' runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Email">
                    <ItemTemplate>
                        <asp:Label ID="lbl_Email" Text='<%# Bind("Email") %>' runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Department">
                    <ItemTemplate>
                        <asp:Label ID="lbl_Department" Text='<%# Bind("Department") %>' runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Designation">
                    <ItemTemplate>
                        <asp:Label ID="lbl_Designation" Text='<%# Bind("Designation") %>' runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Joining_Date">
                    <ItemTemplate>
                        <asp:Label ID="lbl_Joining_Date" Text='<%# Bind("Joining_Date") %>' runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Salary">
                    <ItemTemplate>
                        <asp:Label ID="lbl_Salary" Text='<%# Bind("Salary") %>' runat="server" />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </fieldset>


    <fieldset>
        <legend>Voucher Information</legend>
    </fieldset>

        <asp:RadioButton ID="rbtnOddEnable" runat="server" Text="Enable Odd Numbers" GroupName="number"  AutoPostBack="True" OnCheckedChanged="rbtnOddEnable_CheckedChanged" />
        <asp:RadioButton ID="rbtnEvenEnable" runat="server" Text="Enable Even Numbers" GroupName="number"   AutoPostBack="True" />
        <asp:RadioButton ID="rbtnEnableBoth" runat="server" Text="Enable As You Want" GroupName="number"  AutoPostBack="True" />

        <asp:Button ID="btnsubmit" runat="server" Text="Submit" OnClick="btnsubmit_Click" CssClass="btn btn-default" />

        <asp:GridView ID="voucherGrid" runat="server" AutoGenerateColumns="false" CssClass="table">

            <Columns>
                <asp:TemplateField HeaderText="Select">
                    <ItemTemplate>
                        <asp:CheckBox ID="selectChkBox" runat="server" AutoPostBack="true" />
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="ID">
                    <ItemTemplate>
                        <asp:Label ID="lblid" Text='<%# Eval("ID") %>' runat="server">
                        </asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="VoucherName">
                    <ItemTemplate>
                        <asp:Label ID="lblVoucherName" Text='<%# Eval("VoucherName") %>' runat="server">
                        </asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="NameBehind">
                    <ItemTemplate>
                        <asp:Label ID="lblNameBehind" Text='<%# Eval("NameBehind") %>' runat="server">
                        </asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="CompanyName">
                    <ItemTemplate>
                        <asp:Label ID="lblCompanyName" Text='<%# Eval("CompanyName") %>' runat="server">
                        </asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Odd_Or_Even">
                    <ItemTemplate>
                        <asp:Label ID="lblOdd_Or_Even" Text='<%# Eval("Odd_Or_Even") %>' runat="server">
                        </asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>

    

    <fieldset>
        <asp:Button ID="btninsertGrid" runat="server" Text="Insert Grid" CssClass="btn btn-success" OnClick="btninsertGrid_Click" />
        <asp:Button ID="btndeleteodd" runat="server" Text="Delete Odd Values" CssClass="btn btn-primary" OnClick="btndeleteodd_Click" />
    </fieldset>

    <fieldset>
        <CR:CrystalReportViewer ID="crviewer" runat="server" AutoDataBind="true" />
        <CR:CrystalReportSource ID="crsource" runat="server"></CR:CrystalReportSource>
    </fieldset>
</asp:Content>
